name: Dockerhub

on:
  push:
    branches:
      - "main"
  #   tags:
  #     - "*"
  # pull_request:
  #   branches:
  #     - "*"

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-24.04-arm
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v6
        with:
          context: .
          pull: false
          push: true
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/gitea_runner_arm32:latest
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
